<?php
namespace Tests\Feature;
use App\Models\v1\{Batch,Bir2306Record,Branch,Company,Inventory,Medicine,Transaction,TransactionItem,User};
use Illuminate\Foundation\Testing\DatabaseTransactions;
use Laravel\Sanctum\Sanctum;
use Tests\TestCase;
class QaseReportsWorkflowTest extends TestCase
{
 use DatabaseTransactions;
 private function context(): array { $company=Company::factory()->create(['company_name'=>'Report Pharmacy','tin_number'=>'123-456-789']); $branch=Branch::factory()->create(['company_id'=>$company->company_id,'status'=>'active','branch_name'=>'Main Report Branch']); $user=User::factory()->create(['branch_id'=>$branch->branch_id,'first_name'=>'Report','last_name'=>'Cashier']); Sanctum::actingAs($user,['reports']); return compact('company','branch','user'); }
 private function sale(array $c,float $amount=100,string $payment='Cash',?string $date=null): Transaction { $t=Transaction::factory()->create(['branch_id'=>$c['branch']->branch_id,'user_id'=>$c['user']->user_id,'sub_total'=>$amount+10,'discount'=>10,'total_amount'=>$amount,'vat_amount'=>round($amount/1.12*.12,2),'payment_method'=>$payment,'status'=>'completed','created_at'=>$date ?: now()]); return $t; }
 private function stock(array $c,int $qty=5): array { $m=Medicine::factory()->create(['price'=>20,'stocks'=>$qty,'reorder_level'=>10,'status'=>'active']); $b=Batch::factory()->create(['expiry_date'=>now()->addDays(20),'status'=>'active']); $i=Inventory::factory()->create(['branch_id'=>$c['branch']->branch_id,'medicine_id'=>$m->medicine_id,'batch_id'=>$b->batch_id,'stocks'=>$qty]); return compact('m','b','i'); }
 public function test_tc_090_sales_report_honors_branch_and_date_filters(): void { $c=$this->context(); $this->sale($c,100); $this->sale($c,50,'Cash',now()->subMonths(2)); $url='/api/v1/reports?branch_id='.$c['branch']->branch_id.'&start_date='.today()->subDay()->toDateString().'&end_date='.today()->toDateString(); $this->getJson($url)->assertOk()->assertJsonPath('data.summary.total_revenue',100)->assertJsonPath('data.summary.transaction_count',1); }
 public function test_tc_091_inventory_report_has_value_status_expiry_and_watch_rows(): void { $c=$this->context(); $this->stock($c,5); $this->getJson('/api/v1/reports?branch_id='.$c['branch']->branch_id)->assertOk()->assertJsonPath('data.summary.inventory_value',100)->assertJsonPath('data.summary.low_stock_count',1)->assertJsonPath('data.summary.expiring_30_count',1)->assertJsonCount(1,'data.tables.inventory_watch'); }
 public function test_tc_092_financial_and_cashier_performance_are_computed_from_sales(): void { $c=$this->context(); $this->sale($c,100,'Cash'); $this->sale($c,200,'Gcash'); $r=$this->getJson('/api/v1/reports?branch_id='.$c['branch']->branch_id)->assertOk(); $r->assertJsonPath('data.summary.total_revenue',300)->assertJsonPath('data.summary.average_sale',150)->assertJsonCount(2,'data.charts.payment_mix')->assertJsonPath('data.tables.branch_performance.0.transaction_count',2); }
 public function test_tc_093_report_exports_valid_csv_and_pdf_downloads(): void { $c=$this->context(); $this->sale($c); $csv=$this->get('/api/v1/reports/export?format=csv&branch_id='.$c['branch']->branch_id)->assertOk()->assertHeader('content-type','text/csv; charset=UTF-8'); $this->assertStringContainsString('Transaction ID',$csv->getContent()); $pdf=$this->get('/api/v1/reports/export?format=pdf&branch_id='.$c['branch']->branch_id)->assertOk()->assertHeader('content-type','application/pdf'); $this->assertStringStartsWith('%PDF-1.4',$pdf->getContent()); }
 public function test_tc_094_bir_annual_declaration_uses_completed_year_sales_and_company_details(): void { $c=$this->context(); $year=(int)now()->year-1; $this->sale($c,100,'Cash',now()->setYear($year)); $this->getJson('/api/v1/reports/bir-annual?company_id='.$c['company']->company_id.'&branch_id='.$c['branch']->branch_id.'&year='.$year)->assertOk()->assertJsonPath('data.form_no','2306')->assertJsonPath('data.tin_number','123-456-789')->assertJsonPath('data.net_sales_receipts',100)->assertJsonPath('data.transaction_count',1); }
 public function test_tc_095_bir_record_generates_payment_and_tax_from_transactions(): void { $c=$this->context(); $this->sale($c,112); $p=['company_id'=>$c['company']->company_id,'branch_id'=>$c['branch']->branch_id,'period_from'=>today()->toDateString(),'period_to'=>today()->toDateString(),'payor_tin'=>'123','payor_registered_name'=>'Payer','payor_registered_address'=>'Address','payor_zip_code'=>'6100','nature_of_income_payment'=>'Purchases','atc'=>'WI158','source_reference'=>'BIR-95']; $this->postJson('/api/v1/reports/bir-2306',$p)->assertCreated()->assertJsonPath('data.amount_of_payment','112.00')->assertJsonPath('data.tax_withheld','12.00'); $this->assertDatabaseHas('bir_2306_records',['source_reference'=>'BIR-95']); }
 public function test_tc_096_transaction_records_support_search_payment_sort_and_paging(): void { $c=$this->context(); $this->sale($c,100,'Cash'); $this->sale($c,200,'Gcash'); $this->getJson('/api/v1/reports/transactions?branch_id='.$c['branch']->branch_id.'&payment_method=Gcash&per_page=5')->assertOk()->assertJsonPath('meta.per_page',5)->assertJsonCount(1,'data')->assertJsonPath('data.0.payment_method','Gcash'); }
 public function test_tc_097_all_report_endpoints_require_reports_ability(): void { $c=$this->context(); Sanctum::actingAs($c['user'],['inventory']); foreach(['/api/v1/reports','/api/v1/reports/transactions','/api/v1/reports/bir-annual?company_id=1&branch_id=1&year=2025','/api/v1/reports/export?format=csv'] as $u) $this->getJson($u)->assertForbidden(); $this->postJson('/api/v1/reports/bir-2306',[])->assertForbidden(); }
}
