<?php
namespace Tests\Feature;
use App\Models\v1\{Batch,Branch,Company,Inventory,Medicine,SuperAdmin,SystemAuditLog,Transaction,User};
use Illuminate\Foundation\Testing\DatabaseTransactions;
use Illuminate\Support\Facades\{DB,Hash};
use Laravel\Sanctum\PersonalAccessToken;
use Laravel\Sanctum\Sanctum;
use Tests\TestCase;
class QaseCrossCuttingWorkflowTest extends TestCase
{
 use DatabaseTransactions;
 private function salesContext(int $stock=5): array { $company=Company::factory()->create(); $branch=Branch::factory()->create(['company_id'=>$company->company_id,'status'=>'active']); $user=User::factory()->create(['branch_id'=>$branch->branch_id]); $m=Medicine::factory()->create(['medicine_name'=>'Concurrent Med','price'=>10,'stocks'=>$stock,'status'=>'active','is_dangerous'=>false,'needs_protection'=>false]); $b=Batch::factory()->create(['batch_number'=>'CROSS-'.fake()->unique()->numerify('####'),'expiry_date'=>now()->addYear(),'received_date'=>now(),'mfg_date'=>now()->subYear(),'status'=>'active']); $i=Inventory::factory()->create(['branch_id'=>$branch->branch_id,'medicine_id'=>$m->medicine_id,'batch_id'=>$b->batch_id,'stocks'=>$stock]); Sanctum::actingAs($user,['sales']); return compact('company','branch','user','m','b','i'); }
 private function payload(array $c,int $q): array { $total=$q*10; return ['user_id'=>$c['user']->user_id,'branch_id'=>$c['branch']->branch_id,'transaction_type'=>'regular','sub_total'=>$total,'discount'=>0,'total_amount'=>$total,'used_amount'=>$total,'change'=>0,'payment_method'=>'Cash','items'=>[['medicine_id'=>$c['m']->medicine_id,'inventory_id'=>$c['i']->inventory_id,'batch_id'=>$c['b']->batch_id,'quantity'=>$q]]]; }
 public function test_tc_126_multitable_transaction_rolls_back_every_write_on_failure(): void { $before=[Company::count(),Branch::count()]; try { DB::transaction(function(){ $c=Company::factory()->create(); Branch::factory()->create(['company_id'=>$c->company_id]); throw new \RuntimeException('force rollback'); }); } catch(\RuntimeException $e){ $this->assertSame('force rollback',$e->getMessage()); } $this->assertSame($before,[Company::count(),Branch::count()]); }
 public function test_tc_127_non_get_api_is_protected_without_browser_csrf_dependency(): void { $this->postJson('/api/v1/transaction',[])->assertUnauthorized(); $c=$this->salesContext(); $r=$this->postJson('/api/v1/transaction',$this->payload($c,1)); $this->assertSame(201,$r->status(),$r->getContent()); }
 public function test_tc_128_expired_access_token_is_rejected_after_inactivity_window(): void { $u=User::factory()->create(); $plain=$u->createToken('expired',['dashboard'],now()->subMinute())->plainTextToken; $this->withToken($plain)->getJson('/api/v1/dashboard')->assertUnauthorized(); $this->assertNotNull(PersonalAccessToken::findToken($plain)); }
 public function test_tc_129_competing_sales_cannot_deduct_more_than_locked_stock(): void { $c=$this->salesContext(5); $r=$this->postJson('/api/v1/transaction',$this->payload($c,4)); $this->assertSame(201,$r->status(),$r->getContent()); $this->postJson('/api/v1/transaction',$this->payload($c,4))->assertStatus(422)->assertJsonPath('success',false); $this->assertSame(1,$c['i']->fresh()->stocks); $this->assertDatabaseCount('transactions',1); }
 public function test_tc_130_cors_allows_configured_origin_and_rejects_unlisted_origin(): void { $allowed=$this->call('OPTIONS','/api/v1/catalog',[],[],[],['HTTP_ORIGIN'=>'http://localhost:4200','HTTP_ACCESS_CONTROL_REQUEST_METHOD'=>'GET']); $allowed->assertHeader('Access-Control-Allow-Origin','http://localhost:4200'); $blocked=$this->call('OPTIONS','/api/v1/catalog',[],[],[],['HTTP_ORIGIN'=>'https://evil.invalid','HTTP_ACCESS_CONTROL_REQUEST_METHOD'=>'GET']); $this->assertNull($blocked->headers->get('Access-Control-Allow-Origin')); }
 public function test_tc_131_critical_admin_action_creates_attributed_audit_record(): void { $a=SuperAdmin::create(['first_name'=>'Audit','last_name'=>'Admin','email'=>'audit131@test.local','password'=>Hash::make('Password1!')]); Sanctum::actingAs($a,['super_admin']); $this->postJson('/api/v1/admin/companies',['company_name'=>'Audited Company','company_email'=>'audit-company@test.local','tin_number'=>'AUD-131'])->assertCreated(); $this->assertDatabaseHas('system_audit_logs',['super_admin_id'=>$a->super_admin_id,'action'=>'company_created']); }
 public function test_tc_132_pdf_export_remains_valid_with_heavy_transaction_payload(): void { $c=$this->salesContext(1); for($n=0;$n<250;$n++) Transaction::factory()->create(['branch_id'=>$c['branch']->branch_id,'user_id'=>$c['user']->user_id,'status'=>'completed','total_amount'=>$n+1]); Sanctum::actingAs($c['user'],['reports']); $r=$this->get('/api/v1/reports/export?format=pdf&branch_id='.$c['branch']->branch_id.'&days=90')->assertOk()->assertHeader('content-type','application/pdf'); $this->assertStringStartsWith('%PDF-1.4',$r->getContent()); $this->assertStringEndsWith('%%EOF',$r->getContent()); }
}
