<?php
namespace Tests\Feature;
use App\Models\v1\{Branch,Company,Permission,User};
use Illuminate\Foundation\Testing\DatabaseTransactions;
use Illuminate\Support\Facades\Hash;
use Laravel\Sanctum\Sanctum;
use Tests\TestCase;
class QaseUsersSettingsWorkflowTest extends TestCase
{
 use DatabaseTransactions;
 private function context(): array { $company=Company::factory()->create(); $branch=Branch::factory()->create(['company_id'=>$company->company_id,'status'=>'active']); $admin=User::factory()->create(['branch_id'=>$branch->branch_id,'role'=>'admin','status'=>'approved','password'=>Hash::make('OldPassword1!')]); foreach(['users','settings'] as $name){$p=Permission::firstOrCreate(['permission_name'=>$name],['description'=>$name]);$admin->permissions()->syncWithoutDetaching([$p->permission_id]);} Sanctum::actingAs($admin,['users','settings']); return compact('company','branch','admin'); }
 private function userPayload(array $c,array $x=[]): array { return array_merge(['first_name'=>'Mariah','last_name'=>'Toroy','email'=>fake()->unique()->safeEmail(),'password'=>'Password1!','password_confirmation'=>'Password1!','branch_id'=>$c['branch']->branch_id,'role'=>'staff','address'=>'Bacolod City'],$x); }
 public function test_tc_098_authorized_admin_gets_users_with_role_branch_and_status(): void { $c=$this->context(); User::factory()->create(['branch_id'=>$c['branch']->branch_id,'role'=>'staff','status'=>'approved']); $this->getJson('/api/v1/user')->assertOk()->assertJsonStructure(['data'=>[['user_id','role','status','branch']]])->assertJsonPath('stats.total_users',2); }
 public function test_tc_099_admin_can_create_approved_user_with_default_permissions(): void { $c=$this->context(); foreach(['dashboard','sales','sms','inventory','fefo','drugs','settings'] as $n) Permission::firstOrCreate(['permission_name'=>$n],['description'=>$n]); $r=$this->postJson('/api/v1/user',$this->userPayload($c))->assertCreated()->assertJsonPath('data.status','approved')->assertJsonPath('data.role','staff'); $this->assertTrue(Hash::check('Password1!',User::find($r->json('data.user_id'))->password)); }
 public function test_tc_100_admin_can_edit_then_archive_another_user(): void { $c=$this->context(); $u=User::factory()->create(['branch_id'=>$c['branch']->branch_id]); $this->putJson('/api/v1/user/'.$u->user_id,['first_name'=>'Edited','last_name'=>'User','email'=>$u->email,'address'=>'New','role'=>'pharmacist'])->assertOk()->assertJsonPath('data.first_name','Edited'); $this->deleteJson('/api/v1/user/'.$u->user_id)->assertOk(); $this->assertSoftDeleted('users',['user_id'=>$u->user_id]); }
 public function test_tc_101_pending_registration_can_be_approved(): void { $c=$this->context(); $u=User::factory()->create(['branch_id'=>$c['branch']->branch_id,'status'=>'pending']); $this->postJson('/api/v1/user/update-status/'.$u->user_id.'/approved')->assertOk(); $this->assertSame('approved',$u->fresh()->status); }
 public function test_tc_102_user_moves_only_to_branch_inside_admin_company(): void { $c=$this->context(); $target=Branch::factory()->create(['company_id'=>$c['company']->company_id]); $u=User::factory()->create(['branch_id'=>$c['branch']->branch_id]); $this->postJson('/api/v1/user/update-branch/'.$u->user_id.'/'.$target->branch_id)->assertOk(); $this->assertSame($target->branch_id,$u->fresh()->branch_id); $outside=Branch::factory()->create(); $this->postJson('/api/v1/user/update-branch/'.$u->user_id.'/'.$outside->branch_id)->assertForbidden(); }
 public function test_tc_103_individual_permissions_are_replaced_exactly(): void { $c=$this->context(); $u=User::factory()->create(['branch_id'=>$c['branch']->branch_id]); $p1=Permission::firstOrCreate(['permission_name'=>'inventory'],['description'=>'i']); $p2=Permission::firstOrCreate(['permission_name'=>'sales'],['description'=>'s']); $this->putJson('/api/v1/user/'.$u->user_id.'/permissions',['permission_ids'=>[$p1->permission_id,$p2->permission_id]])->assertOk(); $this->assertEqualsCanonicalizing([$p1->permission_id,$p2->permission_id],$u->permissions()->pluck('permissions.permission_id')->all()); }
 public function test_tc_104_token_without_users_ability_cannot_access_users_module(): void { $c=$this->context(); Sanctum::actingAs($c['admin'],['settings']); foreach(['/api/v1/user','/api/v1/user/'.$c['admin']->user_id,'/api/v1/user/permissions/options'] as $u) $this->getJson($u)->assertForbidden(); }
 public function test_tc_105_settings_load_profile_access_notifications_and_security(): void { $c=$this->context(); $this->getJson('/api/v1/settings')->assertOk()->assertJsonPath('data.profile.user_id',$c['admin']->user_id)->assertJsonStructure(['data'=>['profile','access','notifications','security']]); }
 public function test_tc_106_full_settings_user_updates_notification_preferences(): void { $this->context(); $p=['notify_transactions'=>false,'notify_user_registrations'=>true,'notify_low_stock'=>false,'notify_expiry_alerts'=>true,'notify_security_alerts'=>false,'notify_browser'=>true]; $this->putJson('/api/v1/settings/notifications',$p)->assertOk()->assertJsonPath('data.notify_transactions',false)->assertJsonPath('data.notify_browser',true); }
 public function test_tc_107_change_password_checks_current_and_hashes_new_password(): void { $c=$this->context(); $this->postJson('/api/v1/change-password',['current_password'=>'OldPassword1!','new_password'=>'NewPassword2!','new_password_confirmation'=>'NewPassword2!'])->assertOk()->assertJsonPath('success',true); $this->assertTrue(Hash::check('NewPassword2!',$c['admin']->fresh()->password)); }
 public function test_tc_108_settings_manager_can_create_and_edit_branch(): void { $c=$this->context(); $p=['company_id'=>$c['company']->company_id,'branch_name'=>'New Branch','branch_address'=>'Address','branch_contact'=>'0917','theme_key'=>'emerald','status'=>'active']; $id=$this->postJson('/api/v1/branch',$p)->assertCreated()->json('data.branch_id'); $p['branch_name']='Edited Branch'; $this->putJson('/api/v1/branch/'.$id,$p)->assertOk()->assertJsonPath('data.branch_name','Edited Branch'); }
 public function test_tc_109_settings_management_requires_settings_ability_and_permission(): void { $c=$this->context(); Sanctum::actingAs($c['admin'],['users']); $this->getJson('/api/v1/settings')->assertForbidden(); $this->postJson('/api/v1/branch',[])->assertForbidden(); Sanctum::actingAs($c['admin'],['settings']); $c['admin']->permissions()->detach(); $this->postJson('/api/v1/branch',['company_id'=>$c['company']->company_id,'branch_name'=>'No','branch_address'=>'No','branch_contact'=>'1'])->assertForbidden(); }
}
