<?php

namespace Tests\Feature;

use App\Models\v1\Batch;
use App\Models\v1\Branch;
use App\Models\v1\Company;
use App\Models\v1\Inventory;
use App\Models\v1\Medicine;
use App\Models\v1\User;
use Illuminate\Foundation\Testing\DatabaseTransactions;
use Laravel\Sanctum\Sanctum;
use Tests\TestCase;

class QaseInventoryFefoWorkflowTest extends TestCase
{
    use DatabaseTransactions;
    private function context(): array { $company=Company::factory()->create(); $branch=Branch::factory()->create(['company_id'=>$company->company_id,'status'=>'active']); $user=User::factory()->create(['branch_id'=>$branch->branch_id,'role'=>'staff','status'=>'approved']); Sanctum::actingAs($user,['inventory','fefo']); return compact('company','branch','user'); }
    private function payload(array $c,array $x=[]): array { return array_merge(['medicine_name'=>'Inventory Test','generic_name'=>'Generic Test','pricing_type'=>'branded','cost_price'=>100,'category'=>'Analgesic','reorder_level'=>5,'stocks'=>10,'dosage'=>500,'unit'=>'mg','units_per_box'=>100,'type'=>'Tablet','is_dangerous'=>false,'needs_protection'=>false,'location'=>'Shelf A','mfg_date'=>now()->subYear()->toDateString(),'received_date'=>now()->toDateString(),'expiry_date'=>now()->addMonths(18)->toDateString(),'branch_id'=>$c['branch']->branch_id],$x); }
    private function stock(array $c,int $stocks=5,array $batchData=[]): array { $medicine=Medicine::factory()->create(['status'=>'active','stocks'=>$stocks,'reorder_level'=>5,'price'=>10]); $batch=Batch::factory()->create(array_merge(['batch_number'=>'INV-'.fake()->unique()->numerify('#####'),'expiry_date'=>now()->addYear(),'received_date'=>now(),'mfg_date'=>now()->subYear(),'location'=>'Shelf A','status'=>'active'],$batchData)); $inventory=Inventory::factory()->create(['branch_id'=>$c['branch']->branch_id,'medicine_id'=>$medicine->medicine_id,'batch_id'=>$batch->batch_id,'stocks'=>$stocks,'pcs_per_container'=>10,'container_count'=>1]); return compact('medicine','batch','inventory'); }

    public function test_tc_067_inventory_list_is_scoped_to_active_branch(): void { $c=$this->context(); $s=$this->stock($c); $this->getJson('/api/v1/medicine?branch_id='.$c['branch']->branch_id,['X-Page-Context'=>'inventory'])->assertOk()->assertJsonPath('data.0.inventory_id',$s['inventory']->inventory_id); }
    public function test_tc_068_create_medicine_persists_batch_inventory_and_history(): void { $c=$this->context(); $r=$this->postJson('/api/v1/medicine',$this->payload($c))->assertCreated()->assertJsonPath('success',true); $this->assertDatabaseHas('batches',['batch_id'=>$r->json('data.batch.batch_id'),'status'=>'active']); $this->assertDatabaseHas('batch_histories',['batch_id'=>$r->json('data.batch.batch_id'),'action'=>'created']); }
    public function test_tc_069_pricing_type_derives_ten_or_fifty_percent_markup(): void { $c=$this->context(); $this->postJson('/api/v1/medicine',$this->payload($c))->assertCreated()->assertJsonPath('data.medicine.price','110.00')->assertJsonPath('data.medicine.markup_percent','10.00'); $this->postJson('/api/v1/medicine',$this->payload($c,['medicine_name'=>'Generic Inventory','pricing_type'=>'generic']))->assertCreated()->assertJsonPath('data.medicine.price','150.00')->assertJsonPath('data.medicine.markup_percent','50.00'); }
    public function test_tc_070_cost_price_must_be_positive(): void { $c=$this->context(); $this->postJson('/api/v1/medicine',$this->payload($c,['cost_price'=>0]))->assertStatus(422)->assertJsonPath('message','Cost Price must be greater than 0.'); }
    public function test_tc_071_minimum_twelve_month_shelf_life_is_enforced(): void { $c=$this->context(); $this->postJson('/api/v1/medicine',$this->payload($c,['expiry_date'=>now()->addMonths(11)->toDateString()]))->assertStatus(422)->assertJsonPath('message','Stocks with less than 12 months of remaining shelf life are not accepted.'); }
    public function test_tc_072_manufacture_received_and_expiry_dates_are_ordered(): void { $c=$this->context(); $this->postJson('/api/v1/medicine',$this->payload($c,['mfg_date'=>now()->addDay()->toDateString()]))->assertStatus(422); $this->postJson('/api/v1/medicine',$this->payload($c,['mfg_date'=>now()->toDateString(),'received_date'=>now()->subDay()->toDateString()]))->assertStatus(422); }
    public function test_tc_073_units_per_box_range_is_enforced(): void { $c=$this->context(); foreach([0,10001] as $n) $this->postJson('/api/v1/medicine',$this->payload($c,['units_per_box'=>$n]))->assertStatus(422)->assertJsonPath('message','Units per box must be between 1 and 10000.'); $this->postJson('/api/v1/medicine',$this->payload($c,['units_per_box'=>10000]))->assertCreated(); }
    public function test_tc_074_required_medicine_text_fields_are_validated(): void { $c=$this->context(); foreach(['medicine_name','generic_name','category','type','unit','location'] as $field) { $p=$this->payload($c); unset($p[$field]); $this->postJson('/api/v1/medicine',$p)->assertStatus(422)->assertJsonPath('success',false); } }
    public function test_tc_075_existing_medicine_and_its_batch_can_be_edited(): void { $c=$this->context(); $s=$this->stock($c); $p=$this->payload($c,['inventory_id'=>$s['inventory']->inventory_id,'batch_id'=>$s['batch']->batch_id,'batch_number'=>$s['batch']->batch_number,'medicine_name'=>'Edited Medicine']); $this->putJson('/api/v1/medicine/'.$s['medicine']->medicine_id,$p)->assertOk()->assertJsonPath('data.medicine.medicine_name','Edited Medicine'); $this->assertDatabaseHas('batch_histories',['batch_id'=>$s['batch']->batch_id,'action'=>'updated']); }
    public function test_tc_076_archive_medicine_preserves_record_and_zeros_stock(): void { $c=$this->context(); $s=$this->stock($c); $this->deleteJson('/api/v1/medicine/'.$s['medicine']->medicine_id)->assertOk(); $this->assertDatabaseHas('medicines',['medicine_id'=>$s['medicine']->medicine_id,'status'=>'archived','stocks'=>0]); $this->assertDatabaseHas('inventories',['inventory_id'=>$s['inventory']->inventory_id,'stocks'=>0]); }
    public function test_tc_077_inventory_summary_counts_low_and_out_of_stock(): void { $c=$this->context(); $this->stock($c,4); $this->stock($c,0); $this->getJson('/api/v1/medicine?branch_id='.$c['branch']->branch_id,['X-Page-Context'=>'inventory'])->assertOk()->assertJsonPath('low_stock',2)->assertJsonPath('out_of_stock',1); }
    public function test_tc_078_fefo_list_orders_batches_by_earliest_expiry(): void { $c=$this->context(); $late=$this->stock($c,5,['expiry_date'=>now()->addMonths(6)]); $early=$this->stock($c,5,['expiry_date'=>now()->addMonth()]); $this->getJson('/api/v1/fefo?branch_id='.$c['branch']->branch_id,['X-Page-Context'=>'fefo'])->assertOk()->assertJsonPath('data.0.batch_id',$early['batch']->batch_id)->assertJsonPath('data.1.batch_id',$late['batch']->batch_id); }
    public function test_tc_079_expiry_buckets_have_exact_boundaries(): void { $c=$this->context(); foreach([-1,0,30,31,90,91] as $d) $this->stock($c,1,['expiry_date'=>today()->addDays($d)]); $this->getJson('/api/v1/fefo?branch_id='.$c['branch']->branch_id,['X-Page-Context'=>'fefo'])->assertOk()->assertJsonPath('expired',1)->assertJsonPath('critical',2)->assertJsonPath('warning',2)->assertJsonPath('good',1); }
    public function test_tc_080_batch_location_update_records_history(): void { $c=$this->context(); $s=$this->stock($c); $this->postJson('/api/v1/fefo/'.$s['batch']->batch_id.'/update-location',['location'=>'Cold Shelf B'])->assertOk()->assertJsonPath('data.location','Cold Shelf B'); $this->assertDatabaseHas('batch_histories',['batch_id'=>$s['batch']->batch_id,'action'=>'location_updated']); }
    public function test_tc_081_batch_detail_contains_batch_and_history(): void { $c=$this->context(); $s=$this->stock($c); $this->postJson('/api/v1/fefo/'.$s['batch']->batch_id.'/update-location',['location'=>'B'])->assertOk(); $this->getJson('/api/v1/fefo/'.$s['batch']->batch_id)->assertOk()->assertJsonPath('data.batch.batch_id',$s['batch']->batch_id)->assertJsonCount(1,'data.history'); }
}
