<?php
namespace Tests\Feature;
use App\Models\v1\{Batch,Branch,Company,Inventory,Medicine,RegulatedCustomer,Transaction,TransactionAttachment,TransactionItem,User};
use Illuminate\Foundation\Testing\DatabaseTransactions;
use Laravel\Sanctum\Sanctum;
use Tests\TestCase;
class QaseControlledDrugWorkflowTest extends TestCase
{
 use DatabaseTransactions;
 private function context(): array { $co=Company::factory()->create(); $branch=Branch::factory()->create(['company_id'=>$co->company_id,'status'=>'active']); $user=User::factory()->create(['branch_id'=>$branch->branch_id]); Sanctum::actingAs($user,['drugs']); return compact('co','branch','user'); }
 private function entry(array $c,bool $dangerous=false,bool $protected=true,string $patient='Juan Patient'): array { $med=Medicine::factory()->create(['medicine_name'=>$dangerous?'Danger Med':'Controlled Med','is_dangerous'=>$dangerous,'needs_protection'=>$protected,'status'=>'active','stocks'=>5,'price'=>20]); $batch=Batch::factory()->create(['batch_number'=>'CTRL-'.fake()->unique()->numerify('####'),'expiry_date'=>now()->addYear(),'status'=>'active','location'=>'Vault A']); $inv=Inventory::factory()->create(['branch_id'=>$c['branch']->branch_id,'medicine_id'=>$med->medicine_id,'batch_id'=>$batch->batch_id,'stocks'=>5]); $customer=RegulatedCustomer::create(['full_name'=>$patient,'contact_number'=>'09171234567','id_number'=>'123456789012','formatted_address'=>'Bacolod']); $tx=Transaction::factory()->create(['branch_id'=>$c['branch']->branch_id,'user_id'=>$c['user']->user_id,'patient_name'=>$patient,'regulated_customer_id'=>$customer->regulated_customer_id,'regulated_classification'=>$dangerous?'dangerous':'controlled','regulated_details'=>['prescriber_name'=>'Dr Test','s2_license_number'=>'123456789012'],'status'=>'completed']); TransactionItem::factory()->create(['transaction_id'=>$tx->transaction_id,'medicine_id'=>$med->medicine_id,'batch_id'=>$batch->batch_id,'batch_number'=>$batch->batch_number,'quantity'=>1,'price'=>20]); return compact('med','batch','inv','customer','tx'); }
 public function test_tc_083_logbook_contains_only_regulated_transactions(): void { $c=$this->context(); $e=$this->entry($c); $plain=Medicine::factory()->create(['is_dangerous'=>false,'needs_protection'=>false]); $t=Transaction::factory()->create(['branch_id'=>$c['branch']->branch_id,'user_id'=>$c['user']->user_id]); TransactionItem::factory()->create(['transaction_id'=>$t->transaction_id,'medicine_id'=>$plain->medicine_id]); $this->getJson('/api/v1/controlled-drugs?branch_id='.$c['branch']->branch_id)->assertOk()->assertJsonCount(1,'data.logbook.data')->assertJsonPath('data.logbook.data.0.transaction_id',$e['tx']->transaction_id); }
 public function test_tc_084_controlled_entry_includes_patient_prescriber_and_customer_data(): void { $c=$this->context(); $e=$this->entry($c); $this->getJson('/api/v1/controlled-drugs?branch_id='.$c['branch']->branch_id)->assertOk()->assertJsonPath('data.logbook.data.0.patient_name','Juan Patient')->assertJsonPath('data.logbook.data.0.regulated_details.prescriber_name','Dr Test')->assertJsonPath('data.logbook.data.0.regulated_customer.id_number','123456789012'); }
 public function test_tc_085_dangerous_entry_exposes_yellow_prescription_attachment(): void { $c=$this->context(); $e=$this->entry($c,true,false); TransactionAttachment::create(['transaction_id'=>$e['tx']->transaction_id,'uploaded_by'=>$c['user']->user_id,'category'=>'yellow-prescription','label'=>'Yellow Prescription','original_name'=>'yellow.pdf','mime_type'=>'application/pdf','size_bytes'=>100,'status'=>'active','uploaded_at'=>now()]); $this->getJson('/api/v1/transaction/'.$e['tx']->transaction_id.'/attachments')->assertOk()->assertJsonFragment(['category'=>'yellow-prescription','original_name'=>'yellow.pdf']); }
 public function test_tc_086_logbook_filters_by_date_drug_and_patient(): void { $c=$this->context(); $this->entry($c,false,true,'Matching Patient'); $this->entry($c,true,false,'Other Person'); $this->getJson('/api/v1/controlled-drugs?branch_id='.$c['branch']->branch_id.'&search=Matching&from_date='.today()->toDateString().'&to_date='.today()->toDateString())->assertOk()->assertJsonCount(1,'data.logbook.data')->assertJsonPath('data.logbook.data.0.patient_name','Matching Patient'); }
 public function test_tc_087_controlled_batch_is_disposed_without_deleting_audit_data(): void { $c=$this->context(); $e=$this->entry($c); $this->postJson('/api/v1/controlled-drugs/'.$e['batch']->batch_id.'/dispose')->assertOk(); $this->assertDatabaseHas('batches',['batch_id'=>$e['batch']->batch_id,'status'=>'disposed']); $this->assertDatabaseHas('inventories',['inventory_id'=>$e['inv']->inventory_id,'stocks'=>0]); }
 public function test_tc_088_controlled_batch_location_can_be_updated(): void { $c=$this->context(); $e=$this->entry($c); $this->postJson('/api/v1/controlled-drugs/'.$e['batch']->batch_id.'/update-location',['location'=>'Narcotics Vault'])->assertOk()->assertJsonPath('data.location','Narcotics Vault'); }
 public function test_tc_089_logbook_export_returns_all_filtered_entries(): void { $c=$this->context(); $this->entry($c); $this->entry($c,true,false); $this->getJson('/api/v1/controlled-drugs?branch_id='.$c['branch']->branch_id.'&export=true')->assertOk()->assertJsonCount(2,'data.logbook.data')->assertJsonPath('data.logbook.meta.total',2); }
}
